## Research question 1:

A. Is the question...

1.  Specific and feasible?
2.  Sociological?
3.  Quantitative and about a relationship between at least two variables?

If not, what suggestions do you have about how to improve the question?

B. Is the data set a good fit for the research question?
Will the sample allow the results to be generalized to the target population?

C. Are the variables good fits for the research question?
Do you see any limitations?

## Research question 2:

A. Is the question...

1.  Specific and feasible?
2.  Sociological?
3.  About a relationship between at least two quantitative variables?

If not, what suggestions do you have about how to improve the question?

B. Is the data set a good fit for the research question?
Will the sample allow the results to be generalized to the target population?
(check the data documentation for more information if needed)

C. Will the variables your group member identified let them answer their research question?
If, why not?
Are there any limitations to consider with these variables?

## Which research question would you choose? Why?
