---
title: "Computing access"
---

We will be using R and RStudio to do statistical analysis and Git and GitHub to submit assignments.

I recommend setting up this software on a laptop that you can bring to class.
We will walk through this process in class--see ex-5-18.

To access computing resources for this course, go to the [Duke Container Manager](https://cmgr.oit.duke.edu/containers) website, [cmgr.oit.duke.edu/containers](https://cmgr.oit.duke.edu/containers).

If this is your first time accessing the containers, click on `reserve RStudio` on the *Reservations available* menu on the right.
You only need to do this once, and when you do, you'll see this container moved to the *My reservations* menu on the left.

Next, click on `RStudio` under *My reservations* to access the RStudio instance you'll use for the course.

## Troubleshooting

Note that if you are off campus, you will need to connect to the network via the [Duke VPN](https://oit.duke.edu/what-we-do/services/vpn) in order to use containers.

If you're connected to campus WIFI or the VPn and are still having difficulty launching an RStudio session from your reserved container, go to [status.oit.duke.edu](https://status.oit.duke.edu/) and scroll down to **Teaching and Learning Tools**.
Under this heading you'll find an entry called *Container Manager (CMGR Coursework Containers)*.

-   If the status shows something other than `Operational`, this means there is a known incident with the containers.
    Check back later to see if it's been resolved.
    If there's a deadline coming up soon, email me to let me know that there's an issue.
    I can look into how quickly it might get resolved and decide on what to do about the deadline accordingly.
    Note: We don't anticipate this to happen regularly, the systems are Operational a huge majority of the time!

-   If the status shows `Operational`, this means the system is expected to be working.
    Check your internet connection, if need be, restart your computer to ensure a fresh new connection.
    If your issue persists, email me with details on what you've tried and the errors you see (including verbatim errors and/or screenshots).

Another approach is to request a restart of your container.
To do so, select your container as you usually do and then, instead of Login, click on Request Restart.
Read the warning in the next page, and then click once more to restart your container.

## An alternative to containers: downloading R and RStudio

If you prefer, you may also complete the assignments using local copies of R and RStudio.
This requires slightly more setup than containers.
However, it has advantages once set up--notably, local copies can be used offline.

You will need to download the most recent versions of [R](https://cran.r-project.org/), [RStudio](https://blog--rstudio-com.netlify.app/products/rstudio/download/#download), and [Git](https://git-scm.com/downloads) (all free online).

Then, you will need to connect git and your GitHub account to RStudio.
I recommend [these instructions](https://rfortherestofus.com/2021/02/how-to-use-git-github-with-r/).

If you get stuck, talk to me--I'm happy to help!
