---
title: "SOCIOL333: Quantitative Analysis of Sociological Data Syllabus"
subtitle: "Instructor: Aidan Combs, Reuben-Cooke 141 \n\n Summer Term 1, 2023"
---

::: {.content-visible when-format="html"}
[**Click here**](sociol333-sum23-syllabus.pdf) **to download a PDF copy of the syllabus.**
:::

## Class times

We will meet from 11:15-12:30 Monday through Thursday (except Memorial Day and Juneteenth) in 329 Reuben-Cooke.
See the [schedule](index.html) for more information.

## Office hours

I will be available for 30 minutes before and after each class period.
If these times do not work for you, let me know and we can set up an appointment.

## Textbooks

Our textbook is [**freely available online**](https://openintro-ims.netlify.app/).
It is also possible to order a hard copy if you prefer.

|                                                                         |                          |                                   |                                                                                                                                  |
|-----------------|-----------------|-----------------|----------------------|
| [Introduction to Modern Statistics](https://openintro-ims.netlify.app/) | Çetinkaya-Rundel, Hardin | OpenIntro Inc., 1st Edition, 2021 | Hard copy available [on Amazon](https://www.amazon.com/Introduction-Modern-Statistics-Mine-%C3%87etinkaya-Rundel/dp/1943450145/) |

## Course learning objectives

By the end of the semester, you will...

-   learn to use statistics to shed light on questions about the social world
-   learn to make statistical choices and interpret results in ways consistent with feminist and antiracist scholarship
-   learn to load, manipulate, and visualize data in R
-   learn to effectively communicate results through written assignments and project presentations
-   learn to critically analyze the use of statistics in the world, and know what statistics can and can't tell you about a problem.

## Attendance

You are expected to attend every lecture.
Attending class every day will make it much easier for you to complete our in-class exercises.
In addition, you will have to attend class on workshop days in order to receive full points on the project components.

### What to bring to class

Please bring a laptop to every class.
You will need it to complete in-class exercises.

## Course community

### Duke Community Standard

As a student in this course, you have agreed to uphold the [Duke Community Standard](https://studentaffairs.duke.edu/conduct/about-us/duke-community-standard) as well as the practices specific to this course.

```{=html}
<iframe width="560" height="315" src="https://www.youtube.com/embed/_KN97j30ST4" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen>
</iframe>
```
### Inclusive community

It is my intent that students from all backgrounds and perspectives be well-served by this course, that students' learning needs be addressed both in and out of class, and that the diversity that the students bring to this class be viewed as a resource, strength, and benefit.
It is my intent to present materials and activities that are respectful of diversity and in alignment with [Duke's Commitment to Diversity and Inclusion](https://provost.duke.edu/initiatives/commitment-to-diversity-and-inclusion).
Your suggestions are encouraged and appreciated.
Please let me know ways to improve the effectiveness of the course for you personally, or for other students or student groups.

Furthermore, I would like to create a learning environment for my students that supports a diversity of thoughts, perspectives and experiences, and honors your identities.
To help accomplish this:

-   If you feel like your performance in the class is being impacted by your experiences outside of class, please don't hesitate to come and talk with me. If you prefer to speak with someone outside of the course, your academic dean is an excellent resource.
-   I (like many people) am still in the process of learning about diverse perspectives and identities. If something was said in class (by anyone) that made you feel uncomfortable, please let me know.

### Pronouns

Pronouns are meaningful tools to communicate identities and experiences, and using pronouns supports a campus environment where all community members can thrive.
Please update your gender pronouns in Duke Hub.
You can learn more at the [Center for Sexual and Gender Diversity's website](https://students.duke.edu/belonging/icr/csgd/pronouns/).

### Accessibility

If there is any portion of the course that is not accessible to you due to challenges with technology or the course format, please let me know so we can make appropriate accommodations.

The [Student Disability Access Office (SDAO)](https://access.duke.edu/students) is available to ensure that students are able to engage with their courses and related assignments.
Students should be in touch with the Student Disability Access Office to [request or update accommodations](https://access.duke.edu/requests) under these circumstances.

### Communication

All lecture notes, assignment instructions, an up-to-date schedule, and other course materials may be found on the course website: [soc333-sum23.github.io/](https://soc333-sum23.github.io/).

Announcements will be emailed through Sakai Announcements periodically.
Please check your email regularly to ensure you have the latest announcements for the course.

### Where to get help

If you have a question during class, feel free to ask it!
There are likely other students with the same question, so by asking you will create a learning opportunity for everyone.
I will also be available before and after each class session as well as by email.

Check out the [course support](https://soc333-sum23.github.io/course-support.html) tab for more resources.

### Email

If you have a question you do not want to bring up in class, you are welcome to email me directly.
Barring extenuating circumstances, I will respond to emails within 48 hours Monday - Friday.
I will respond more slowly to emails sent Friday evening - Sunday.

## Assessments

The assessments in this course are designed to help you successfully achieve the course learning objectives.

### In-class exercises

We will spend a significant portion of our class time learning to apply concepts from lectures by doing in-class exercises.
You will be expected to turn in the exercises from lecture before the next class period.
For example, you will be expected to submit the Tuesday exercises before class starts on Wednesday.
These will be graded for completion--i.e., you will get full points if you show that you made a good-faith attempt to answer all parts.
You will receive full points for the in-class exercise portion of the final grade if you submit at least 80% of the exercises on time.

### Homework

You will complete 1-2 homework assignments during the course of the summer term.
In homework, you will apply what you've learned during lecture to complete data analysis tasks.
You may discuss homework assignments with other students; however, homework should be completed and submitted individually.

### Project

The purpose of the [project](https://soc333-sum23.github.io/project-description.html) is to apply what you've learned throughout the semester to analyze a sociological research question of your choice.
You will complete the project in several component parts that will be graded individually, and will assemble the parts into a complete paper and presentation at the end of the semester.
You will bring a draft of most components to class to workshop with your classmates before submitting them for grading.
Your grade will be determined by both the quality of your submitted work and your participation in the peer feedback process.
More information about the project will be provided during the semester.

## Grading

The final course grade will be calculated as follows:

| Category           | Percentage |
|--------------------|------------|
| Homework           | 20%        |
| In-class exercises | 30%        |
| Project            | 50%        |

Your final letter grade will be determined based on the following thresholds:

| Letter Grade | Final Course Grade |
|--------------|--------------------|
| A            | \>= 93             |
| A-           | 90 - 92.99         |
| B+           | 87 - 89.99         |
| B            | 83 - 86.99         |
| B-           | 80 - 82.99         |
| C+           | 77 - 79.99         |
| C            | 73 - 76.99         |
| C-           | 70 - 72.99         |
| D+           | 67 - 69.99         |
| D            | 63 - 66.99         |
| D-           | 60 - 62.99         |
| F            | \< 60              |

### Regrade requests

I do everything in my power to grade assignments consistently, accurately, and fairly the first time.
I will only change a grade later if I made a clear and undeniable error--doing otherwise compromises the fairness and consistency I strive for.

To ask a question about your grade or request a regrade, please email me.

## Course policies

### Academic honesty

**TL;DR: Don't cheat!**

Please abide by the following as you work on assignments in this course:

-   **Collaboration:** You may discuss individual homework assignments with other students; however, you may not directly share (or copy) code or write up with other students. Unauthorized sharing (or copying) of the code or write up will be considered a violation for all students involved.
-   **Reusing code**: Unless explicitly stated otherwise, you may make use of online resources (e.g. StackOverflow) for coding examples on assignments. If you directly use code from an outside source (or use it as inspiration), you must explicitly cite where you obtained the code. Any recycled code that is discovered and is not explicitly cited will be treated as plagiarism.

Any violations in academic honesty standards as outlined in the [Duke Community Standard](https://studentaffairs.duke.edu/conduct/about-us/duke-community-standard) and those specific to this course will automatically result in a 0 for the assignment and will be reported to the [Office of Student Conduct](https://studentaffairs.duke.edu/conduct) for further action.

### Late work

-   Homework, project components, and in-class exercises may be submitted up to 3 days late. Details on the associated penalties will be provided with the assignment information.

### Extenuating circumstances

Things happen that make it impossible to submit every assignment on time.
The grading schemes for each assignment build in some flexibility to ensure you are not penalized for occasional missed classes or deadlines.

In the case that you must miss class, please let me know.
My slides will be made accessible to all students.
You will still be expected to complete that day's in-class exercises, but you will have to do so on your own.

If there are circumstances that are having a longer-term impact on your academic performance, please talk to me and/or let your academic dean know, as they can be a resource.

*Note: If you've read this far in the syllabus, email me a picture of your pet if you have one or your favorite meme!*

### Attendance policy

-   **COVID Symptoms, Exposure, or Infection:** Student health, safety, and well-being are the university's top priorities. To help ensure your well-being and the well-being of those around you, **please do not come to class** **if you have tested positive for COVID-19 or have possible symptoms and have not yet been tested.** If any of these situations apply to you, you must follow university guidance related to the ongoing COVID-19 pandemic and current health and safety protocols. If you are experiencing any COVID-19 symptoms, [contact student health](https://coronavirus.duke.edu/testing/#symptomatic-testing) ([dshcheckin\@duke.edu](mailto:dshcheckin@duke.edu), 919-681-9355). Learn more about current university policy related to COVID-19 at [https://coronavirus.duke.edu](https://coronavirus.duke.edu/). To keep the university community's safe and healthy as possible, you will be expected to follow these guidelines. Please reach out to me and your academic dean as soon as possible if you need to quarantine or isolate so that we can discuss arrangements for your continued participation in class.
-   **Inclement weather:** In the event of inclement weather or other connectivity-related events that prohibit class attendance, I will notify you how we will make up missed course content and work.  Asynchronous catch-up methods may apply.
-   **Religious accommodations:** Students are permitted by university policy to be absent from class to observe a religious holiday. Accordingly, Trinity College of Arts & Sciences and the Pratt School of Engineering have established procedures to be followed by students for notifying their instructors of an absence necessitated by the observance of a religious holiday. Please submit requests for religious accommodations at the beginning of the semester so that we can work to make suitable arrangements well ahead of time. You can find the policy and relevant notification form here: <https://trinity.duke.edu/undergraduate/academic-policies/religious-holidays>.
