---
title: "Course support"
---

Getting a little stuck and feeling a little frustrated by the course material is a good thing -- it means that you are appropriately challenged by the material and are learning something new!
I and your classmates are here to support you through this learning process.

## Lectures

If you have a question during lecture, feel free to ask it!
There are likely other students with the same question, so by asking you will create a learning opportunity for everyone.

## Office hours

I will come to the classroom 30 minutes prior to class and stay 30 minutes after class.
You are encouraged to come early or stay late to ask questions about the course content and assignments.
A lot of questions are most effectively answered in-person, so office hours are a valuable resource.
I encourage each and every one of you to take advantage of it!

If it works better for you to meet at a different time, please email me to set up an appointment.

## Email

My email address is [ahc26\@duke.edu](mailto:ahc26@duke.edu).
Please email me with any questions you have that you don't wish to ask in class.
Barring extenuating circumstances, I will respond to emails within 48 hours Monday - Friday.
I take weekends off (and encourage you to do so as well).
As such, I will respond more slowly to emails sent Friday evening - Sunday.

## Academic support

There are times may need help with the class that is beyond what I can provide.
In those instances, I encourage you to visit the Academic Resource Center.
The [Academic Resource Center (ARC)](https://arc.duke.edu) offers free services to all students during their undergraduate careers at Duke.
Services include Learning Consultations, Peer Tutoring and Study Groups, ADHD/LD Coaching, Outreach Workshops, and more.
Because learning is a process unique to every individual, they work with each student to discover and develop their own academic strategy for success at Duke.
Contact the ARC to schedule an appointment.
Undergraduates in any year, studying any discipline can benefit!
Contact [ARC\@duke.edu](mailto:arc@duke.edu), 919-684-5917.

## Technical support

For help with computing, reach out to the [Duke Office of Information Technology](https://oit.duke.edu/help/).
A functioning computing setup is a critical part of this course.
If something breaks, please reach out to me as soon as possible.

## Mental health and wellness

If your mental health concerns and/or stressful events negatively affect your daily emotional state, academic performance, or ability to participate in your daily activities, many resources are available to help you through difficult times. 
Duke encourages all students to access these resources.

-   **CAPS:** [Duke Counseling & Pyschological Services (CAPS)](https://studentaffairs.duke.edu/caps) helps Duke Students enhance strengths and develop abilities to successfully live, grow and learn in their personal and academic lives. CAPS recognizes that we are living in unprecedented times and that the changes, challenges and stressors brought on by the COVID-19 pandemic have impacted everyone, often in ways that are tax our well-being. CAPS offers many services to Duke undergraduate students, including brief individual and group counseling, couples counseling and more. CAPS staff also provides outreach to student groups, particularly programs supportive of at-risk populations, on a wide range of issues impacting them in various aspects of campus life. CAPS provides services to students via Telehealth. To initiate services, you can contact their front desk at 919-660-1000.
-   **DuWell:** (919) 681-8421, provides Moments of Mindfulness (stress management and resilience building) and meditation programming to assist students in developing a daily emotional well-being practice. To see schedules for programs please see <https://studentaffairs.duke.edu/duwell>. All are welcome and no experience necessary.
-   **DukeReach:** Provides comprehensive outreach services to identify and support students in managing all aspects of well-being. If you have concerns about a student's behavior or health visit the website for resources and assistance: <http://studentaffairs.duke.edu/dukereach>.
-   **TimelyCare:** (formerly known as Blue Devils Care) An online platform that is a convenient, confidential, and free way for Duke students to receive 24/7 mental health support through TalkNow and scheduled counseling: <https://bluedevilscare.duke.edu>.
-   **Two-Click Support:** Duke Student Government and DukeReach partnership that connects students to help in just two clicks: <https://bit.ly/TwoClickSupport>.

## Course costs

-   **Textbook:** The textbook and all other readings for this course are freely available on the web.
-   **Laptops:** Each student is expected to have a laptop they can bring to each lecture. Any laptop that will connect to campus wifi and allow you to download a roughly 1gb program should be fine.

If you are having difficulty with costs associated with this course, here are some resources:

-   [Contact the financial aid office](https://financialaid.duke.edu/contact "https://financialaid.duke.edu/contact") (whether or not you are on aid).
    They have loans and resources for connecting students with programs on campus that might be able to help alleviate these costs.

-   DukeLIFE offers [loaner laptops](https://dukelife.duke.edu/technology-assistance-program/) for eligible students.

-   [The Link](https://oit.duke.edu/what-we-do/services/link-equipment) may also offer short-term laptop rentals.

## **Assistance with Sakai**

For technical help with Sakai, contact the Duke OIT Service Desk at [oit.duke.edu/help](https://oit.duke.edu/help).
You can also access the self-service help documentation for Sakai [here](https://sakai-duke.screenstepslive.com/s/sakai_support).

Note that we will be making minimal use of Sakai in this course (primarily for announcements and grade book).
All assignment submission will take place on GitHub.
