---
title: "Project"
callout-icon: false
---

# Proposal

## How to complete and submit

To get some practice with our new computing workflow, you will write this assignment in a Quarto document.

First, you need to locate and clone the repository ([instructions](https://soc333-sum23.github.io/computing-clonerepo.html)). Go to our [course github organization](https://github.com/orgs/soc333-sum23/repositories) and find the repository called **c1_proposal_yourusername**. Clone that repository. Open the document called *c1_proposal.qmd*. This is a template document where you will put your work.

Commit your changes regularly. When you are done, render the document and push your work to github ([instructions](https://soc333-sum23.github.io/computing-clonerepo.html#how-to-commit-and-push-changes))

## Workshop questions

Read your group members' proposed research questions. Then create a new GitHub issue on each of their repositories, copy and paste in these questions, and answer them.

### Research question 1:

A. Is the question...

1.  Specific and feasible?
2.  Sociological?
3.  About a relationship between at least two quantitative variables?

B. Is the data set a good fit for the research question? Will the sample allow the results to be generalized to the target population? (check the data documentation for more information if needed)

C. Will the variables your group member identified let them answer their research question? If, why not? Are there any limitations to consider with these variables?

D. What suggestions do you have about how to improve the research question or other aspects of the proposal?

### Research question 2:

A. Is the question...

1.  Specific and feasible?
2.  Sociological?
3.  About a relationship between at least two quantitative variables?

B. Is the data set a good fit for the research question? Will the sample allow the results to be generalized to the target population? (check the data documentation for more information if needed)

C. Will the variables your group member identified let them answer their research question? If, why not? Are there any limitations to consider with these variables?

D. What suggestions do you have about how to improve the research question or other aspects of the proposal?

### Which research question would you choose? Why?

## Details

In this component, you will think through two possible research questions and data sets. Using the feedback provided by your classmates, you will choose one to pursue further.

### Data

You will need to find two data sets: one for each of your research questions. You may write additional research questions on a single data set if you would like additional feedback, but in all cases, you must consider and present at least two data sets in total.

I highly recommend selecting [data sets included with the openintro package](https://www.openintro.org/data/). There is all kinds of interesting data freely available on the internet, but it is a good idea to stick with openintro because their data sets are clean and easy to work with. We already have a lot to do in just 6 weeks, and so will not be covering how to prepare "messy" data for analysis (I recommend a data science course like STA 199 for this!). If you really want to use a data set from elsewhere instead, talk to me.

Not all openintro data sets will work for this course because not all of them lend themselves to sociological questions (see below for research question requirements). Choose data sets that have something to do with people, that contain real (not simulated, not demo) data, and that contain a bare minimum of 50 observations and two interesting variables. Avoid data sets that are used extensively to demonstrate concepts in the textbook. You may not choose questions that are similar to or the same as those used as book examples.

I recommend the below data sets, all of which are included in openintro. Click on the links to see some basic information about them. To access any of them in R, just load the openintro package, then use their names.

-   [`acs12`](https://www.openintro.org/data/index.php?data=acs12)
-   [`cia_factbook`](https://www.openintro.org/data/index.php?data=cia_factbook)
-   [`county_2019`](https://www.openintro.org/data/index.php?data=county_2019)
-   [`county_complete`](https://www.openintro.org/data/index.php?data=county_complete)
-   [`evals`](https://www.openintro.org/data/index.php?data=evals)
-   [`gpa`](https://www.openintro.org/data/index.php?data=gpa)
-   [`gss2010`](https://www.openintro.org/data/index.php?data=gss2010)
-   [`hfi`](https://www.openintro.org/data/index.php?data=hfi)
-   [`hsb2`](https://www.openintro.org/data/index.php?data=hsb2)
-   [`labor_market_discrimination`](https://www.openintro.org/data/index.php?data=labor_market_discrimination)
-   [`military`](https://www.openintro.org/data/index.php?data=military)
-   [`mn_police_use_of_force`](https://www.openintro.org/data/index.php?data=mn_police_use_of_force)
-   [`ncbirths`](https://www.openintro.org/data/index.php?data=ncbirths)
-   [`piracy`](https://www.openintro.org/data/index.php?data=piracy)
-   [`resume`](https://www.openintro.org/data/index.php?data=resume)
-   [`satgpa`](https://www.openintro.org/data/index.php?data=satgpa)
-   [`sowc_demographics`](https://www.openintro.org/data/index.php?data=sowc_demographics)
-   [`voter_count`](https://www.openintro.org/data/index.php?data=voter_count)
-   [`yrbss`](https://www.openintro.org/data/index.php?data=yrbss)

### Version to bring to class for peer review (Thursday, May 23)

You are required to propose a minimum of 2 research questions, to be answered with 2 separate data sets, that you're interested in potentially using for the final project. If you would like to receive feedback on more than two research questions, you may optionally submit additional questions. You will review each others' proposals in groups of 2-3. After peer review, you will be responsible for updating your draft and submitting for grading according to the requirements below.

For each research question, you should:

-   Clearly state the specific research question. Make sure it fulfills the following requirements:

    -   Must fulfill the requirements of a good research question: specific, feasible, sociological
    -   Must involve a relationship between at least two variables
    -   Must be answerable with quantitative data and simple statistics

-   Additionally, provide some supporting information:

    -   What is your target population?
    -   Write down a hypothesis stating what you expect to find. Give a brief (\~1-2 sentence) justification for why you expect this.

-   Identify the data set you would use to answer the research question and provide some information about it. Address the following questions:

    -   When and how was it originally collected?
    -   Is it an observational study or an experiment?
    -   Who or what was sampled, and how many observations are there?
    -   What variables would you use to answer your question?
    -   Discuss the strengths and weaknesses of this data set with respect to your research question and target population. Does the sampling strategy make it a good fit? What are its limitations?

-   Provide a glimpse of your data

    -   Use the `glimpse()` function to provide a first look at the data set.

### Version to submit for grading (Tuesday, May 28, 11:59pm)

After peer review, incorporate your peers' feedback into your draft. You should revise your questions if they need it. In addition, add \~1 paragraph of thoughts about which question you should ultimately choose to move forward with. In that paragraph, answer the following questions:

-   Which question do you think you should pursue for your final project?
-   Why is this the right choice? Discuss quality of the research question (in terms of being specific, feasible, and sociological) and the ability of the data set to answer the question well.

Submit one Quarto document containing your revised research questions and this summary paragraph.

# Grading

|                                                                                                              |     |
|------------------------------------------------------------|------------|
| Peer feedback: draft completion; quality of feedback given; peer feedback incorporated into final submission | 30% |
| Research questions                                                                                           | 20% |
| Data set descriptions                                                                                        | 20% |
| Data set glimpses                                                                                            | 10% |
| Paragraph on research question choice                                                                        | 10% |
| Workflow and formatting                                                                                      | 10% |

Each part will be graded as follows:

-   **Meets expectations**: All required elements are completed and are accurate. The narrative is written clearly, all tables and visualizations are nicely formatted, and the work would be presentable in a professional setting.

-   **Close to expectations**: There are some elements missing and/or inaccurate. There are some issues with formatting.

-   **Partial credit:** Major elements missing. Work is not neatly formatted and would not be presentable in a professional setting.

-   **Does not meet expectations**: Not completed.

It is critical to check feedback on your project proposal. Even if you earn full credit, it may not mean that your proposal is perfect. Just like you are expected to incorporate feedback from your peers into your graded proposal, you will be expected to incorporate feedback from me into the relevant sections of your final paper. The degree to which you address feedback will be a component of your final paper grade.

::: callout-tip
# Why?

There are three main purposes of the project proposal:

-   To get you thinking about the project early so you can get a head start on refining your question, finding your data, and doing your analysis.
-   To ensure that the data you wish to analyze, methods you plan to use, and the scope of your analysis are feasible and will allow you to be successful.
-   To give you practice talking about analysis ideas and plans with your peers.
:::
