---
title: "Project description"
callout-icon: false
---

# Timeline

[Proposal](#proposal): bring to class DATE, due DATE

[Descriptive statistics](#descriptives): bring to class DATE, due DATE

[Results](#results) bring to class DATE, due DATE

[Paper](#paper) bring to class DATE, due DATE

[Presentation + slides](#presentation) due at time of in-class presentation on DATE

# Overview

**TL;DR**: *Ask a question you're curious about and answer it with a data set of your choice. This is your project in a nutshell.*

Throughout the course of the summer term, you will be performing a statistical analysis to answer a sociological research question of your choosing.
You will provide the results of your analysis in two ways: through a research presentation to the class and through a final paper.
You will complete the project individually, but throughout the semester you will be helping each other develop your ideas by giving peer feedback at various stages.

::: callout-tip
## Why?

Statistics is a tool for answering questions we have about how the world is and how it works.
When people --- researchers, sports analysts, marketing professionals, etc --- use statistics outside of statistics classes, it is because they have a question that can be answered by looking at quantitative data.
This project is meant to introduce you to the process of doing quantitative analysis and presenting your results in a way that resembles how you will use statistics after you leave this class.
:::

# Project Assignment Structure

You will have to turn in five components for this project.
This may sound daunting, but it is not meant to be.
The first three components (the proposal, descriptive statistics, and results) are meant to build on each other and help you construct the last two (the paper and presentation).

Each component with the exception of the presentation has two due dates.
You will first bring your assignment to class for peer feedback.
Then, you will have an opportunity to edit the assignment before turning it in to me for feedback and grading.
You will be expected to incorporate feedback given by both your peers and by me to make future revisions better --- this will be a component of your grade.

## Submission Format

Everything with the exception of the presentation should be written as a Quarto document.
All data cleaning, analysis, and visualizations should be done in that single file, so that your entire document is 100% reproducible (i.e., someone else should be able to take your file, click "render" or "run", and recreate your results and visualizations).

::: callout-tip
## Why?

*Why peer feedback?* Very few people work in isolation.
We constantly get feedback from colleagues, and learning how to give and receive such feedback in a way that makes projects better is essential for coursework as well as for most jobs.

*Why Quarto?* While there is, of course, a learning curve associated with writing analyses in a new way (ie, in Quarto instead of text editors you are more used to, like Word and Google Docs), it is a skill worth learning for statistical analysis in particular.
Why?
Quarto allows you to easily make your work entirely reproducible.
You will be able to give a collaborator one single document that shows all steps in the analysis process as well as all necessary background information and explanation.
This makes your work easy for others to understand, check, and modify.
Using Quarto also encourages you to learn good coding practices, right from the beginning.
You will be explaining what you do as you go along, and the way files are compiled will encourage you to write code that runs correctly in order--which may not sound like much, but it's actually quite easy to get disorganized when coding in other ways.
We will go over Quarto in class so that you have all the information and support you need to learn it.
:::

# Proposal {#proposal}

## Details

In this component, you will think through two possible research questions and data sets.
Using the feedback provided by your classmates, you will choose one to pursue further.

### Data

You will need to find two data sets: one for each of your research questions.
You may write additional research questions on a single data set if you would like additional feedback, but in all cases, you must consider and present at least two data sets in total.
In other words, additional questions on a single data set are extra; they do not count towards your required two questions.

I highly recommend selecting [data sets included with the openintro package](https://www.openintro.org/data/).
There is all kinds of interesting data freely available on the internet, but it is a good idea to stick with openintro because their data sets are clean and easy to work with.
We already have a lot to do in just 6 weeks, and so will not be covering how to prepare "messy" data for analysis (I recommend a data science course like STA 199 for this!).
If you really, really want to use a data set from elsewhere, talk to me.

Not all openintro data sets will work for this course because not all of them lend themselves to sociological questions (see below for research question requirements--they must have to do with people living in a social system).
Choose data sets that have something to do with people, that contain real (not simulated, not demo) data, and that contain a bare minimum of 50 cases and two interesting variables.

The below data sets are good places to start, though you may propose others so long as they allow you to write a research question about people and the social systems they live in.

```         
-   acs12
-   cia_factbook
-   county_2019
-   county_complete
-   dds.discr
-   evals
-   fatal_police_shootings
-   gpa
-   gss2010
-   hfi
-   hsb2
-   labor_market_discrimination
-   loans_full_schema
-   military
-   mn_police_use_of_force
-   ncbirths
-   piracy
-   resume
-   satgpa
-   sowc_demographics
-   voter_count
-   yrbss
```

### Version to bring to class for peer review (DATE)

You are required to propose a minimum of 2 research questions, to be answered with 2 separate data sets, that you're interested in potentially using for the final project.
If you would like to receive feedback on more than two research questions, you may optionally submit additional questions.
You will review each others' proposals in groups of 2-3.
After peer review, you will be responsible for updating your draft and submitting for grading according to the requirements below.

For each research question, you should:

-   Clearly state the specific research question.
    Make sure it fulfills the following requirements:

    -   Must be specific and well-formulated (see slides LINK)
    -   Must involve a relationship between at least two variables
    -   Must be *sociological* in some way--this is a sociology class, after all. In other words, it has to have something to do with people living in a social system. If you are not sure whether your question meets this requirement, ask!

-   Additionally, provide some supporting information:

    -   What is your target population?
    -   Write \~1 paragraph giving any necessary background information and explaining why the question is interesting to study.
    -   Write down a hypothesis stating what you expect to find. Give a brief (\~1-2 sentence) justification for why you expect this.

-   Identify the data set you would use to answer the research question and provide some information about it.
    Address the following questions:

    -   When and how was it originally collected?
    -   Who or what was sampled, and how many observations are there?
    -   What variables would you use to answer your question?
    -   Why is this data set a good fit for your research question?
    -   Briefly (in \~2-3 sentences) address any ethical concerns. If none, explain why there are none.

-   Provide a glimpse of your data

    -   Place the file containing your data in the `data` folder of the project repo.
    -   Use the `glimpse()` function to provide a glimpse of the data set.

### Version to submit for grading (DATE)

After peer review, incorporate your peers' feedback into your draft.
In addition, add \~1 paragraph of thoughts about which question you should ultimately choose to move forward with.
In that paragraph, answer the following questions:

-   Which question do you think you should pursue for your final project?
-   Why is this the right choice? Discuss fit between the research question and data set, feasibility, and value of the research question.

Submit one Quarto document containing your revised research questions and this summary paragraph.

## Grading

|                                                                                                              |     |
|-----------------------------------------------|------------------------|
| Peer feedback: draft completion; quality of feedback given; peer feedback incorporated into final submission | 30% |
| Research questions                                                                                           | 20% |
| Data set descriptions                                                                                        | 20% |
| Data set glimpses                                                                                            | 10% |
| Paragraph on research question choice                                                                        | 10% |
| Workflow and formatting                                                                                      | 10% |

Each component will be graded as follows:

-   **Meets expectations (full credit)**: All required elements are completed and are accurate.
    The narrative is written clearly, all tables and visualizations are nicely formatted, and the work would be presentable in a professional setting.

-   **Close to expectations (half credit)**: There are some elements missing and/or inaccurate.
    There are some issues with formatting.

-   **Does not meet expectations (no credit)**: Major elements missing.
    Work is not neatly formatted and would not be presentable in a professional setting.

It is critical to check feedback on your project proposal.
Even if you earn full credit, it may not mean that your proposal is perfect.
Just like you are expected to incorporate feedback from your peers into your graded proposal, you will be expected to incorporate feedback from me into the relevant sections of your final paper.
The degree to which you address feedback will be a component of your final paper grade.

::: callout-tip
## Why?

There are three main purposes of the project proposal:

-   To get you thinking about the project early so you can get a head start on refining your question, finding your data, and doing your analysis.
-   To ensure that the data you wish to analyze, methods you plan to use, and the scope of your analysis are feasible and will allow you to be successful.
-   To give you practice talking about analysis ideas and plans with your peers.
:::

# Descriptive Statistics {#descriptives}

In this component, you will explore the variables you will use in your analysis.

## Details

There will be no peer review version for this component.
Instead, we will make time available to work on it in class so that you can work through any issues with the help of your colleagues and I.

### Version to bring to class (DATE)

Come to class having already started the assignment.
At minimum, identify your variables, load your data, run the `summary()` and/or `table()` functions on the variables you are using in your analysis, and try to create one plot.
Completing as much as you can prior to class will allow you to make the best use of the opportunity to ask questions in class.

I encourage you to submit questions ahead of time by DETAILS or come to class prepared to ask specific questions.
Your preparation for and participation in the class session will be part of your grade for this component.

### Version to submit for grading (DATE)

Please submit this assignment as a single Quarto document.

-   Part 1: Understanding your variables

    -   Write down your research question
    -   Write down the names of the variables you will use in your analysis (i.e., what you need to type to call them in R)
    -   For each variable, tell me:
        -   What purpose it serves in your analysis (independent variable, dependent variable, mediating variable, moderating variable, etc)
        -   What kind of variable it is (binary, categorical, ordinal, continuous)
        -   What the range or possible responses are
        -   For categorical (ordinal, nominal, and binary) variables, tell me what your reference category will be (or, if you need to see the data to determine this, how you will decide once you do)

-   Part 2: Visualizing your data

    -   Load your final project data set
    -   For each variable:
        -   Run the `summary()` (for continuous variables) or `table()` (for all other types of variables) function on the variable. Describe the results. Does anything about them surprise you?
        -   Note how many missing values there are. Hint: use the `useNA = "always"` option if using `table()`. Does this seem reasonable?
        -   Make a histogram of the variable's distribution.
        -   Describe the distribution. Does anything surprise you? For continuous and ordinal variables, tell me which distribution terms discussed in class apply. I.e., is the variable's distribution normal? Unimodal? Skewed? Uniform?
    -   Make a plot showing the relationship between your primary independent and dependent variables. Depending on your variable types, this could be a scatter plot, box plot, bar chart, etc.
        -   Interpret your plot in \~2-3 sentences. Does it appear these variables are associated with one another? Does anything about the relationship surprise you? Is it consistent or inconsistent with your hypothesis?

## Grading

|                                                                        |     |
|------------------------------------------------------|------------------|
| Preparation for work in class: assignment started, class participation | 30% |
| Part 1                                                                 | 30% |
| Part 2                                                                 | 30% |
| Workflow and formatting                                                | 10% |

::: callout-tip
## Why?

Before doing any inferential statistics, you should always get a good understanding of what the distributions of your variables look like.
This will help you head off problems later.
For example, looking at the distributions of your variables will reveal if data is missing when you don't expect it to be.
It also might clue you in on interesting patterns you may want to investigate further.
Looking at bivariate associations between variables gives you a sense of what the relationship between them looks like, which will help you interpret inferential statistics.
:::

# Results {#results}

In this component, you will test your hypothesis and present the results of your test(s).

## Details

Bring a full draft of this component to class for peer review on DATE.

Incorporate your peer feedback and turn in a version for grading on DATE.

The required elements of this component are as follows:

-   Part 1: Analysis plan

    -   State your research question, hypothesis, and variables you intend to use (from the proposal, updated as necessary).
    -   Select an analytic method to use to answer this question. This must be either an inferential method or a linear regression.
    -   Explain why your chosen method is appropriate for your question and your variables
    -   What are the limitations of this strategy?

-   Part 2: Analysis results

    -   Perform the analysis you described in part 1.
    -   Present the results as either a figure or a table, as appropriate.
    -   Interpret your results. What do they tell you about your research question? Do they support your hypothesis?
    -   What *don't* your results tell you about your research question? In other words, what are some reasonable next steps for future research in this area?

## Grading

|                                                                                                              |     |
|-----------------------------------------------|------------------------|
| Peer feedback: draft completion; quality of feedback given; peer feedback incorporated into final submission | 30% |
| Part 1                                                                                                       | 30% |
| Part 2                                                                                                       | 30% |
| Workflow and formatting                                                                                      | 10% |

::: callout-tip
## Why?

It is generally not very convincing to only show descriptive statistics of your sample, because ultimately, we do not care about your sample specifically--we want to know something about the entire target population.
If you were somehow able to measure the entire target population, would you be likely to see the same pattern?
Inferential statistics allow you to answer that question.

Completing this component will allow you the chance to receive feedback on your analytic strategy and refine it prior to submitting your full paper.
:::

# Paper {#paper}

The necessary components of the report are below.
You are free to add additional sections as necessary.
I intend that you are able to pull in much of this information from the previous three components of this project (the proposal, descriptive statistics, and results).
However, you must edit to ensure that the report reads well as a cohesive whole, and you must also address any relevant feedback you received on those components.
**You must not simply paste your three previous assignments together in one document; this will not score well.**

Be selective in what you include in your final write-up.
The goal is to write a cohesive narrative that demonstrates a thorough and comprehensive analysis rather than explain every step of the analysis.

## Timeline

Bring a full draft to class on DATE for peer review.
The final revised draft is due on the last day of summer term finals, DATE.

## Overall requirements

-   Your full paper must be completed in the `report.qmd` file and must be reproducible.
    Before you finalize your write up, make sure the printing of code chunks is off with the option `echo: false` in the YAML.

-   The complete paper, including visualizations, should be no more than 10 pages long.
    There is no minimum page requirement; however, you should comprehensively address all of the analysis in your report.

::: callout-note
To check how many pages your report is, open it in your browser and go to File \> Print \> Save as PDF and review the number of pages.
:::

-   You must include and interpret at least one figure that usefully displays your data. You may choose where it makes most sense to include this.

## Paper sections

### Introduction

This section includes an introduction to the project motivation and research question.

#### Grading criteria

The research question and motivation are clearly stated in the introduction, including citations for the data source and any external research.
The research question is well formulated and the data set fits the question.
The data are clearly described, including a description about how the data were originally collected and a concise definition of the variables relevant to understanding the report.

### Data and methodology

This section includes a brief description of your data and your analysis process.
Describe the data and variables you will use in analysis.
Be clear about what purpose your variables serve and how they are operationalized.
Explain your analysis strategy and why this strategy is appropriate for your question and variables.
Though you may show descriptive analysis, you should go beyond it--ie, you should use one or more of the hypothesis testing techniques we have discussed in class.

#### Grading criteria

The analysis steps are appropriate for the data and research question.

### Results

This is where you will discuss your overall finding and describe the key results from your analysis.
Present the results of your analysis using figures and/or tables, as appropriate.
The goal is not to interpret every single element of an output shown, but instead to address the research questions, using the interpretations to support your conclusions.
Focus on the variables that help you answer the research question and that provide relevant context for the reader.

#### Grading criteria

The analysis results are clearly assessed and interesting findings from the analysis are described.
Interpretations are used to to support the key findings and conclusions, rather than merely listing, e.g., the interpretation of every model coefficient.

### Discussion

In this section you'll include a summary of what you have learned about your research question along with statistical arguments supporting your conclusions.
In addition, discuss the limitations of your analysis and provide suggestions on ways the analysis could be improved.
Any potential issues pertaining to the reliability and validity of your data and appropriateness of the statistical analysis should also be discussed here.
In short, describe what your results reveal about the research question, as well as what they *do not* say.
Lastly, this section will include ideas for future work.

#### Grading criteria

Overall conclusions from analysis are clearly described, and the analysis results are put into the larger context of the subject matter and original research question.
There is thoughtful consideration of potential limitations of the data and/or analysis, and ideas for future work are clearly described.

### Organization + formatting

This is an assessment of the overall presentation and formatting of the written report.

#### Grading criteria

The report is neatly written and organized with clear section headers and appropriately sized figures with informative labels.
Numerical results are displayed with a reasonable number of digits, and all visualizations are neatly formatted.
All citations and links are properly formatted.
All code, warnings, and messages are suppressed.
The paper is no longer than 10 pages.

## Report grading

The final paper grade is broken down as follows.

|                             |     |
|-----------------------------|-----|
| Introduction                | 10% |
| Data and methodology        | 20% |
| Results                     | 30% |
| Discussion                  | 20% |
| Organization and formatting | 10% |
| Peer review                 | 10% |

# Presentation + slides {#presentation-slides}

## Slides

In addition to the written report, you will also create presentation slides and deliver a presentation that summarizes and showcases your project.
Introduce your research question and data set, showcase visualizations, and discuss the primary conclusions.
These slides should serve as a brief visual addition to your written report and will be graded for content and quality.

You can create your slides with any software you like (Keynote, PowerPoint, Google Slides, etc.).

::: callout-note
You can also use Quarto to make your slides!
While we won't be covering making slides with Quarto in the class, I am happy to help you with it in office hours.
It's no different than writing other documents with Quarto, so the learning curve will not be steep!
:::

The slide deck should have about 6 content slides + 1 title slide.
Here is a *suggested* outline as you think through the slides; you [**do not**]{.underline} have to use this exact format for the 6 slides.

-   Title Slide
-   Slide 1: Introduce the topic and motivation
-   Slide 2: Introduce the data
-   Slide 3: Highlights of the descriptive statistics
-   Slide 4-5: Results: Inference/modeling/other analysis
-   Slide 6: Conclusions + future work

## Presentation {#presentation}

Presentations will take place in class during the last class of the semester (DATE).
**The presentation should be about 10 minutes**.
There will be time for a few questions after each presentation.

## Grading criteria

The presentation is clear and informative.
The slides are neat, professional, and support rather than distract from the presenter.

# Overall project grading

The overall project grade breakdown is as follows:

|                            |     |
|----------------------------|-----|
| **Proposal**               | 15% |
| **Descriptive statistics** | 15% |
| **Results**                | 15% |
| **Final paper**            | 40% |
| **Slides + presentation**  | 15% |

## Grading summary

Grading of the project will take into account the following:

-   Content - What is the quality of research and/or policy question and relevancy of data to those questions?
-   Correctness - Are statistical procedures carried out and explained correctly?
-   Writing and Presentation - What is the quality of the statistical presentation, writing, and explanations?
-   Creativity and Critical Thought - Is the project carefully thought out? Are the limitations carefully considered? Does it appear that time and effort went into the planning and implementation of the project?

A general breakdown of scoring is as follows:

-   *90%-100%*: Outstanding effort. Student understands how to apply all statistical concepts, can put the results into a cogent argument, can identify weaknesses in the argument, and can clearly communicate the results to others.
-   *80%-89%*: Good effort. Student understands most of the concepts, puts together an adequate argument, identifies some weaknesses of their argument, and communicates most results clearly to others.
-   *70%-79%*: Passing effort. Student has misunderstanding of concepts in several areas, has some trouble putting results together in a cogent argument, and communication of results is sometimes unclear.
-   *60%-69%*: Struggling effort. Student is making some effort, but has misunderstanding of many concepts and is unable to put together a cogent argument. Communication of results is unclear.
-   *Below 60%*: Student is not making a sufficient effort.

## Late work policy

**There is no late work accepted on this project.** Be sure to turn in your work early to avoid any technological mishaps.
