---
title: "Project"
callout-icon: false
editor: visual
---

# Results {#results}

In this component, you will perform an inferential statistical test that provides evidence regarding your research question. The results of inferential analyses allow you to draw some conclusions about the population that your data came from.

The expectation is that you perform one test to provide evidence for one question.

If your research question involves multiple sub-questions (e.g., is of the form "how does X affect Y and also how does Z affect Y" or "how does X affect Y and also how does X affect Z"), you are welcome and encouraged to perform additional statistical tests to investigate the additional sub-questions. In this case, I will score your tests separately and count only the highest score towards your grade.

```{r, include = FALSE}
library(tidyverse)
library(infer)
library(openintro)
```

## Workshop questions

Read your partner's results section. Then create a new GitHub issue on their repository, copy and paste in these questions, and answer them.

*If these questions don't make sense for where your partner is at--eg, if their assignment is not done--do as much as you can, then ask what they need help with, and spend the rest of your time on that. The main goal here is that everyone gets feedback that is useful to them.*

-   Part 1: Check your partner's answers for each of the following pieces. Are they correct? If not, what would you have written instead? (ask for more information on their variables or data if needed. Write "none" if not present.)

    -   Explanatory variable and type
    -   Response variable and type
    -   Null hypothesis
    -   Alternative hypothesis
    -   Choice of statistical test

-   Part 2

    -   If your group member doesn't have results yet:

        -   look through their code. Can you help them find the mistake?

    -   If your group member does have results:

        -   do you agree with their choice to reject or fail to reject the null?
        -   are their conclusions about their research question valid?

    -   Read over their stated limitations/next steps. Are they valid? What else can you think of here?

## Details

Bring a full draft of this component to class for peer review on **Thursday June 15**.

Incorporate your peer feedback and turn in a version for grading by **Tuesday June 20, 11:59pm**.

The required elements of this component are as follows:

-   Part 1: Analysis plan

    -   State your research question (from earlier project components, updated as necessary).

    -   Provide some information on your explanatory and response variables (from earlier project components, updated as necessary):

        -   What is/are your **explanatory** (independent) variable(s)? For each, say if it is a numeric variable, a categorical variable with two levels, or a categorical variable with three or more levels.

        -   What is/are your **response** (dependent) variable(s)? For each, say if it is a numeric variable, a categorical variable with two levels, or a categorical variable with three or more levels.

    -   Hypotheses:

        -   State your null hypothesis.

        -   State your alternative hypothesis.

    -   What statistical test will you use? Explain why this test is the right choice. (\~1-3 sentences)

    -   If necessary, make any necessary changes to your data frame (filtering out observations or creating variables). This code can be copied from component 2 (updated as necessary).

-   Part 2: Analysis results

    -   Perform the analysis you described in part 1. Display your p value.

    -   Plot your null distribution. Shade the part corresponding to your p value.

    -   Interpret the p value for your test. Using a threshold of p \< .05, do you reject or fail to reject your null hypothesis? (\~2-3 sentences)

    -   What conclusions can you draw about your research question? (\~1-3 sentences)

    -   What *don't* your results tell you about your research question? In other words, what are some reasonable next steps for future research in this area? (\~2-4 sentences)

## Grading

|                                                                                                              |     |
|--------------------------------------------------------------------------------------------------------------|-----|
| Peer feedback: draft completion; quality of feedback given; peer feedback incorporated into final submission | 20% |
| Part 1                                                                                                       | 35% |
| Part 2                                                                                                       | 35% |
| Workflow and formatting                                                                                      | 10% |

::: callout-tip
## Why?

It is generally not very convincing to only show descriptive statistics of your sample, because ultimately, we do not care about your sample specifically--we want to know something about the entire target population. If you were somehow able to measure the entire target population, would you be likely to see the same pattern? Inferential statistics allow you to answer that question.

Completing this component will allow you the chance to receive feedback on your analytic strategy and refine it prior to submitting your full paper.
:::
