---
title: "Project"
callout-icon: false
---

# Presentation + slides {#presentation-slides}

## Slides

In addition to the written report, you will also create presentation slides and deliver a presentation that summarizes and showcases your project. Introduce your research question and data set, showcase visualizations, and discuss the primary conclusions.

You can create your slides with any software you like (Keynote, PowerPoint, Google Slides, etc.).

::: callout-note
You can also use Quarto to make your slides! While we won't be covering making slides with Quarto in class, I am happy to help you with it in office hours. It's no different than writing other documents with Quarto, so the learning curve will not be too steep. The main benefit is that you can include your code to create your plots right in your presentation, so no screenshotting or saving plots as separate files.
:::

The slide deck should have about 5-6 content slides + 1 title slide. Here is a *suggested* outline as you think through the slides; you [**do not**]{.underline} have to use this exact format.

-   Title Slide
-   Slide 1: Introduce the topic and motivation
-   Slide 2: Introduce the data and your variables
-   Slide 3: Descriptive results
-   Slide 4: Inferential results
-   Slide 5: Conclusions and limitations
-   Slide 6: Future work

## Presentation {#presentation}

Presentations will take place in class during the last two classes of the semester (**Thursday June 22** and **Monday June 26**). The presentation should be between 6 and 10 minutes. There will be time for a few questions after each presentation.

## Grading criteria

The presentation is clear and informative. The slides are neat, professional, and support rather than distract from the presenter.
