---
title: "Project"
callout-icon: false
---

# Paper {#paper}

The final assignment of the semester is to compile the analysis you've done into a single, cohesive report---something that you could send to a colleague or a supervisor who wanted to know your findings and how you obtained them.

The requirements for this paper are below. I intend that you are able to pull in some of this information from the previous three components of this project (the proposal, descriptive statistics, and results). However, you must edit to ensure that your report meets all requirements listed here, all your code runs, and everything reads well as a cohesive whole. You must also address any relevant feedback you received on previous components. **Do not just paste your three previous assignments together in one document; this will not meet requirements and will score poorly.**

## Workshop questions

Read your group member's paper. Then create a new GitHub issue on their repository, copy and paste in these questions, and answer them.

### Introduction

-   Did the writer clearly state the research question and target population?
-   Did the writer clearly and compellingly explain why we should care about the answer to the research question?
-   How could this section be improved?

### Data and methodology

-   Did the writer adequately describe their data? Things that should be included: Observational study or an experiment? Who or what do the observations represent? Why is this data a good fit for the research question?
-   Did the writer provide the variables they will use in their analysis?
    -   And tell you how they are measured in the data--eg, whether they are numeric, categorical, etc, and what the response options are?
    -   And provide and discuss appropriate univariate descriptive statistics (mean/median/quartiles or table)?
    -   And tell you what purpose each variable serves in analysis: explanatory, response, or something else?
-   Did the writer note what kind of hypothesis test they would use?
-   How could this section be improved?

### Results

-   Did the writer include an appropriate figure showing the relationship between their explanatory and response variables?

-   Did they include the p value from their hypothesis test? Did they correctly state whether they reject or fail to reject the null?

-   Is their interpretation of their results clear and tied back to their research question? (ie, do they go beyond "I reject the null hypothesis"---what does the decision mean for the answer to the research question?)

-   Do the writer's conclusions about the research question follow logically from the results presented?

-   How could this section be improved?

### Discussion and conclusion

-   Are the writer's conclusions clear?
-   Does the writer discuss at least two possible limitations of their results? Are these limitations reasonable?
-   Does the writer provide ideas for future work?
-   How could this section be improved?

### Writing and organization

-   Is the writing clear, concise, and error-free?
-   Is content included in the right sections?
-   Does the flow of the paper make sense?
-   How could this element be improved?

## Timeline

Upload a full draft to GitHub by the start of class on **Thursday, June 2** for peer review. The final revised draft is due on **Monday, June 24, 11:59pm**.

## Overall requirements

-   Your full paper must be completed in the `c5-paper.qmd` file. The section headings are provided for you, as are some starter code chunks. Feel free to add more chunks if necessary---to do so, either copy/paste or go to `Code -> Insert Chunk` (in the top menu bar).

-   There is no specific minimum or maximum length requirement. I will grade based on the content of your paper, not its length.

    -   Your paper should be long enough to allow you to comprehensively address all of the points in these instructions in your report. Be concise, however. You do not need to provide information that is not related to what is requested here (that means you will leave out some things from the previous assignments).
    -   The suggested length for individual sections is provided in the section headings on this page. These are what I expect to be the average length for a concise but complete section---but your mileage may vary; they are suggestions, not requirements.

-   You may cite reputable external sources if you wish. This is optional, but discussing what others have done and found may help you motivate your question and discuss the significance of the conclusions. If you do, use the format (lastnames year) in the text---for example, "Previous work has found X (Cheng and Johnson 2020)." Additionally, include a References section at the end of the document with full citation information (any format). I recommend using Zotero or another reference manager to put this together. It doesn't need to look pretty; just ensure the necessary information is included.

## Paper sections

### Introduction (\~1-3 paragraphs)

-   Introduce the reader to the research question and target population.
-   Provide any necessary background information and some motivation. Why is it important that we know the answer to this question?

### Data and methodology (\~3-5 paragraphs)

-   Describe the data and what you know about how it was collected. Was it an observational study or an experiment? Who or what do your observations represent? Why is this data a good fit for your research question?
-   Describe the variables you will use in your analysis, including how they are operationalized in your data set. Present their univariate descriptive statistics and describe anything notable. Be clear about what purpose your variables serve (explanatory/response/something else).
-   Note any changes you made to your data (filtering out observations or creating new variables).
-   Explain your analysis strategy and why this strategy is appropriate for your question and variables.

### Results (\~1-3 paragraphs)

-   Present results pertaining to the relationship between your explanatory and response variables (descriptive *and* inferential)

    -   Your descriptive results should be presented using at least one appropriate and interpretable figure
    -   Obtain and interpret your p value(s) from your hypothesis testing. You do not need to include the visualization of the sampling distribution (this is generally a tool for the analyst; it's not necessary for a reader).

-   Interpret your results in the context of your research question. What do they tell us about the answer to that question?

### Discussion and conclusion (\~3-4 paragraphs)

-   Summarize what we have learned about your research question from your analysis.
-   Discuss the limitations of your analysis and conclusions (**include at least 2 limitations**). Provide suggestions on how this work could be improved. Any potential issues pertaining to the reliability and validity of your data and appropriateness of the statistical analysis should also be discussed here.
-   Provide ideas for future work. Now that we have the answer to this research question, what's next?

### Writing and organization

-   This is an assessment of the overall quality of the writing and organization of the report
-   Writing should be clear, concise, and error-free
-   Section headers should be clear and content should be included in the correct sections

### Revision process

-   A complete draft was pushed to GitHub before class on Thursday, Jun 20
-   Feedback provided to group members was thoughtful and useful
-   Feedback from previous components and from group members has been incorporated into the final draft

## Report grading

The final paper grade is broken down as follows.

|                           |     |
|---------------------------|-----|
| Introduction              | 10% |
| Data and methodology      | 20% |
| Results                   | 30% |
| Discussion and conclusion | 20% |
| Writing and organization  | 10% |
| Revision process          | 10% |
